from datetime import datetime
from typing import Protocol

from domain.business.campaign import CampaignDailyMetric
from domain.business.sku import SKUDailyMetric
from domain.business.snapshot import BusinessStateSnapshot
from domain.issue.evidence import Evidence
from domain.issue.models import Issue


class SnapshotRepository(Protocol):
    def save(self, snapshot: BusinessStateSnapshot) -> None: ...
    def get(self, snapshot_id: str) -> BusinessStateSnapshot | None: ...
    def latest(self) -> BusinessStateSnapshot | None: ...
    def current_version(self) -> int: ...


class IssueRepository(Protocol):
    def save_issue(self, issue: Issue) -> None: ...
    def save_evidence(self, evidence: Evidence) -> None: ...
    def get_issue(self, issue_id: str) -> Issue | None: ...
    def get_evidence(self, evidence_id: str) -> Evidence | None: ...
    def list_open(self) -> list[Issue]: ...
    def list_by_snapshot(self, snapshot_id: str) -> list[Issue]: ...
    def list_evidence(self, evidence_ids: list[str]) -> list[Evidence]: ...


class BusinessRepository(Protocol):
    def save_sku_daily(self, rows: list[SKUDailyMetric]) -> None: ...
    def save_campaign_daily(self, rows: list[CampaignDailyMetric]) -> None: ...
    def list_sku_daily(
        self, sku_id: str, start: datetime, end: datetime
    ) -> list[SKUDailyMetric]: ...
    def list_campaign_daily(
        self, campaign_id: str, start: datetime, end: datetime
    ) -> list[CampaignDailyMetric]: ...
    def list_all_sku_daily(self) -> list[SKUDailyMetric]: ...
    def list_all_campaign_daily(self) -> list[CampaignDailyMetric]: ...
